name: Bug Report
description: Report a bug or issue with an MCP server
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong
    validations:
      required: true
  
  - type: checkboxes
    id: affected-component
    attributes:
      label: Tutorial/Server Affected
      description: Which tutorial or server is this bug related to?
      options:
        - label: Tutorial 1 - Basic MCP Server
        - label: Tutorial 2 (future)
        - label: Data Analysis Server
        - label: File System Server
        - label: Other (specify in description)
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe the expected outcome
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually occurred
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 14.1, Windows 11, Ubuntu 22.04
      placeholder: macOS 14.1
    validations:
      required: true
  
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "3.12.0"
    validations:
      required: true
  
  - type: input
    id: uv-version
    attributes:
      label: UV Version
      description: Run `uv --version`
      placeholder: "0.1.0"
  
  - type: input
    id: mcp-version
    attributes:
      label: MCP Package Version
      description: Run `uv pip show mcp` or `pip show mcp`
      placeholder: "1.24.0"
  
  - type: input
    id: claude-version
    attributes:
      label: Claude Desktop Version
      description: If applicable
      placeholder: "0.7.0"
  
  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: |
        Paste any error messages or relevant logs here.
        For Claude Desktop, check: ~/Library/Logs/Claude/mcp*.log (macOS) or %APPDATA%\Claude\logs (Windows)
      render: shell
      placeholder: Paste error messages here
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or configuration files
      placeholder: Any additional information
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: I've tested with the latest version
          required: false
        - label: I've included error logs/messages
          required: false